-- Ensure continent and city tables exist for fresh databases
CREATE TABLE IF NOT EXISTS continent (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS city (
    id INT AUTO_INCREMENT PRIMARY KEY,
    logo_url VARCHAR(500),
    image_url VARCHAR(500),
    name VARCHAR(255) NOT NULL,
    continent_id INT,
    INDEX idx_city_continent (continent_id),
    CONSTRAINT fk_city_continent FOREIGN KEY (continent_id) REFERENCES continent(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed continents (no drop/create here)
INSERT INTO continent (id, name) VALUES
    (1,'Africa'),
    (2,'Europe'),
    (3,'Asia & Pacific'),
    (4,'North America'),
    (5,'South America')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Seed cities from teammate dump; keep IDs stable, strip leading slashes on image paths
INSERT INTO city (id, logo_url, image_url, name, continent_id) VALUES
    (1,'https://images.lumacdn.com/discovery/lagos-icon.png','/assets/cities/images/lagos.jpg','Lagos',1),
    (2,'https://images.lumacdn.com/discovery/nairobi-icon.png','/assets/cities/images/nairobi.jpg','Nairobi',1),
    (3,'https://images.lumacdn.com/discovery/bangkok-icon.png','/assets/cities/images/bangkok.jpg','Bangkok',3),
    (4,'https://images.lumacdn.com/discovery/bangalore-icon.png','/assets/cities/images/bengaluru.jpg','Bengaluru',3),
    (5,'https://images.lumacdn.com/discovery/brisbane-icon.png','/assets/cities/images/brisbane.jpg','Brisbane',3),
    (6,'https://images.lumacdn.com/discovery/dubai-icon.png','/assets/cities/images/dubai.jpg','Dubai',3),
    (7,'https://images.lumacdn.com/discovery/hcm-icon.png','/assets/cities/images/hochiminhcity.jpg','Ho Chi Minh City',3),
    (8,'https://images.lumacdn.com/discovery/hk-icon.png','/assets/cities/images/hongkong.jpg','Hong Kong',3),
    (9,'https://images.lumacdn.com/discovery/hnl-icon.png','/assets/cities/images/honolulu.jpg','Honolulu',3),
    (10,'https://images.lumacdn.com/discovery/jakarta-icon.png','/assets/cities/images/jakarta.jpg','Jakarta',3),
    (11,'https://images.lumacdn.com/discovery/kl-icon.png','/assets/cities/images/kualalumpur.jpg','Kuala Lumpur',3),
    (12,'https://images.lumacdn.com/discovery/manila-icon.png','/assets/cities/images/manila.jpg','Manila',3),
    (13,'https://images.lumacdn.com/discovery/mel-icon.png','/assets/cities/images/melbourne.jpg','Melbourne',3),
    (14,'https://images.lumacdn.com/discovery/mumbai-icon.png','/assets/cities/images/mumbai.jpg','Mumbai',3),
    (15,'https://images.lumacdn.com/discovery/newdelhi-icon.png','/assets/cities/images/newdelhi.jpg','New Delhi',3),
    (16,'https://images.lumacdn.com/discovery/seoul-icon.png','/assets/cities/images/seoul.jpg','Seoul',3),
    (17,'https://images.lumacdn.com/discovery/sg-icon.png','/assets/cities/images/singapore.jpg','Singapore',3),
    (18,'https://images.lumacdn.com/discovery/sydney-icon.png','/assets/cities/images/sydney.jpg','Sydney',3),
    (19,'https://images.lumacdn.com/discovery/taipei-icon.png','/assets/cities/images/taipei.jpg','Taipei',3),
    (20,'https://images.lumacdn.com/discovery/telaviv-icon.png','/assets/cities/images/telaviv-yafo.jpg','Tel Aviv-Yafo',3),
    (21,'https://images.lumacdn.com/discovery/tokyo-icon.png','/assets/cities/images/tokyo.jpg','Tokyo',3),
    (22,'https://images.lumacdn.com/discovery/atlanta-icon.png','/assets/cities/images/atlanta.jpg','Atlanta',4),
    (23,'https://images.lumacdn.com/discovery/austin-icon.png','/assets/cities/images/austin.jpg','Austin',4),
    (24,'https://images.lumacdn.com/discovery/boston-icon.png','/assets/cities/images/boston.jpg','Boston',4),
    (25,'https://images.lumacdn.com/discovery/calgary-icon.png','/assets/cities/images/calgary.jpg','Calgary',4),
    (26,'https://images.lumacdn.com/discovery/chicago-icon.png','/assets/cities/images/chicago.jpg','Chicago',4),
    (27,'https://images.lumacdn.com/discovery/dallas-icon.png','/assets/cities/images/dallas.jpg','Dallas',4),
    (28,'https://images.lumacdn.com/discovery/denver-icon.png','/assets/cities/images/denver.jpg','Denver',4),
    (29,'https://images.lumacdn.com/discovery/houston-icon.png','/assets/cities/images/houston.jpg','Houston',4),
    (30,'https://images.lumacdn.com/discovery/vegas-icon.png','/assets/cities/images/lasvegas.jpg','Las Vegas',4),
    (31,'https://images.lumacdn.com/discovery/la-icon.png','/assets/cities/images/losangeles.jpg','Los Angeles',4),
    (32,'https://images.lumacdn.com/discovery/cdmx-icon.png','/assets/cities/images/mexicocity.jpg','Mexico City',4),
    (33,'https://images.lumacdn.com/discovery/miami-icon.png','/assets/cities/images/miami.jpg','Miami',4),
    (34,'https://images.lumacdn.com/discovery/montreal-icon.png','/assets/cities/images/montreal.jpg','Montréal',4),
    (35,'https://images.lumacdn.com/discovery/nyc-icon.png','/assets/cities/images/newyork.jpg','New York',4),
    (36,'https://images.lumacdn.com/discovery/philly-icon.png','/assets/cities/images/philadelphia.jpg','Philadelphia',4),
    (37,'https://images.lumacdn.com/discovery/phx-icon.png','/assets/cities/images/phoenix.jpg','Phoenix',4),
    (38,'https://images.lumacdn.com/discovery/portland-icon.png','/assets/cities/images/portland.jpg','Portland',4),
    (39,'https://images.lumacdn.com/discovery/slc-icon.png','/assets/cities/images/saltlakecity.jpg','Salt Lake City',4),
    (40,'https://images.lumacdn.com/discovery/sd-icon.png','/assets/cities/images/sandiego.jpg','San Diego',4),
    (41,'https://images.lumacdn.com/discovery/sf-icon.png','/assets/cities/images/sanfrancisco.jpg','San Francisco',4),
    (42,'https://images.lumacdn.com/discovery/seattle-icon.png','/assets/cities/images/seattle.jpg','Seattle',4),
    (43,'https://images.lumacdn.com/discovery/toronto-icon.png','/assets/cities/images/toronto.jpg','Toronto',4),
    (44,'https://images.lumacdn.com/discovery/vancouver-icon.png','/assets/cities/images/vancouver.jpg','Vancouver',4),
    (45,'https://images.lumacdn.com/discovery/dc-icon.png','/assets/cities/images/washington,dc.jpg','Washington, DC',4),
    (46,'https://images.lumacdn.com/discovery/waterloo-icon.png','/assets/cities/images/waterloo.jpg','Waterloo',4),
    (47,'https://images.lumacdn.com/discovery/bogota-icon.png','/assets/cities/images/bogota.jpg','Bogotá',5),
    (48,'https://images.lumacdn.com/discovery/ba-icon.png','/assets/cities/images/buenosaires.jpg','Buenos Aires',5),
    (49,'https://images.lumacdn.com/discovery/medellin-icon.png','/assets/cities/images/medellin.jpg','Medellín',5),
    (50,'https://images.lumacdn.com/discovery/rio-icon.png','/assets/cities/images/riodejaneiro.jpg','Rio de Janeiro',5),
    (51,'https://images.lumacdn.com/discovery/sp-icon.png','/assets/cities/images/saopaulo.jpg','São Paulo',5),
    (60,'https://images.lumacdn.com/discovery/ams-icon.png','/assets/cities/images/amsterdam.jpg','Amsterdam',2),
    (61,'https://images.lumacdn.com/discovery/bcn-icon.png','/assets/cities/images/barcelona.jpg','Barcelona',2),
    (62,'https://images.lumacdn.com/discovery/berlin-icon.png','/assets/cities/images/berlin.jpg','Berlin',2),
    (63,'https://images.lumacdn.com/discovery/brussels-icon.png','/assets/cities/images/brussels.jpg','Brussels',2),
    (64,'https://images.lumacdn.com/discovery/budapest-icon.png','/assets/cities/images/budapest.jpg','Budapest',2),
    (65,'https://images.lumacdn.com/discovery/cph-icon.png','/assets/cities/images/copenhagen.jpg','Copenhagen',2),
    (66,'https://images.lumacdn.com/discovery/dublin-icon.png','/assets/cities/images/dublin.jpg','Dublin',2),
    (67,'https://images.lumacdn.com/discovery/geneva-icon.png','/assets/cities/images/geneva.jpg','Geneva',2),
    (68,'https://images.lumacdn.com/discovery/hamburg-icon.png','/assets/cities/images/hamburg.jpg','Hamburg',2),
    (69,'https://images.lumacdn.com/discovery/helsinki-icon.png','/assets/cities/images/helsinki.jpg','Helsinki',2),
    (70,'https://images.lumacdn.com/discovery/istanbul-icon.png','/assets/cities/images/istanbul.jpg','Istanbul',2),
    (71,'https://images.lumacdn.com/discovery/lausanne-icon.png','/assets/cities/images/lausanne.jpg','Lausanne',2),
    (72,'https://images.lumacdn.com/discovery/lisbon-icon.png','/assets/cities/images/lisbon.jpg','Lisbon',2),
    (73,'https://images.lumacdn.com/discovery/london-icon.png','/assets/cities/images/london.jpg','London',2),
    (74,'https://images.lumacdn.com/discovery/madrid-icon.png','/assets/cities/images/madrid.jpg','Madrid',2),
    (75,'https://images.lumacdn.com/discovery/milan-icon.png','/assets/cities/images/milan.jpg','Milan',2),
    (76,'https://images.lumacdn.com/discovery/munich-icon.png','/assets/cities/images/munich.jpg','Munich',2),
    (77,'https://images.lumacdn.com/discovery/paris-icon.png','/assets/cities/images/paris.jpg','Paris',2),
    (78,'https://images.lumacdn.com/discovery/prague-icon.png','/assets/cities/images/prague.jpg','Prague',2),
    (79,'https://images.lumacdn.com/discovery/rome-icon.png','/assets/cities/images/rome.jpg','Rome',2),
    (80,'https://images.lumacdn.com/discovery/stockholm-icon.png','/assets/cities/images/stockholm.jpg','Stockholm',2),
    (81,'https://images.lumacdn.com/discovery/vienna-icon.png','/assets/cities/images/vienna.jpg','Vienna',2),
    (82,'https://images.lumacdn.com/discovery/warsaw-icon.png','/assets/cities/images/warsaw.jpg','Warsaw',2),
    (83,'https://images.lumacdn.com/discovery/zurich-icon.png','/assets/cities/images/zurich.jpg','Zurich',2)
ON DUPLICATE KEY UPDATE
    logo_url = VALUES(logo_url),
    image_url = VALUES(image_url),
    name = VALUES(name),
    continent_id = VALUES(continent_id);
